In [10]:
import numpy as np
import pandas as pd
import random as rd
from random import randint
import operator
import matplotlib.pyplot as plt

In [11]:
file_index=20 #matrix que se quiere leer
filename = str(file_index//10) + str(file_index%10) + ".txt"
file = open(filename, "r")
data = file.read().split()
number_of_cities = int(data[0])
distances_matrix = []
for row in range(number_of_cities):
    distances_row = []
    for col in range(number_of_cities):
        index = 1 + row*number_of_cities + col
        distances_row.append(float(data[index]))

    distances_matrix.append(distances_row)
        
file.close()

In [12]:
c=pd.DataFrame(distances_matrix)
for i in c:
    c[i][i]=1000000

In [13]:
c

0             1             2             3
0  1000000.0000       43.0116       36.0555       33.5410
1       53.0116  1000000.0000       17.0711       21.1803
2       46.0555       17.0711  1000000.0000       15.0000
3       43.5410       21.1803       15.0000  1000000.0000

In [16]:
route=[0]
wdistances=c
wdistances=wdistances.drop([0])
place=0
factor=1.10
while len(wdistances)>0:
    wdistances=wdistances.sort_values(by=[place])
    wdistances=wdistances.reset_index()
    closest_city=wdistances[place][0] 
    options=[]
    for i in range(len(wdistances)):
        if wdistances[place][i]<=closest_city*factor:
            options.append(wdistances['index'][i])
        ind=rd.randint(0,len(options)-1)
        place=options[ind]
    wdistances=wdistances.set_index('index')
    route.append(place)
    wdistances=wdistances.drop([place])
route.append(0)

In [17]:
#Route
route

[0, 1, 2, 3, 0]

In [18]:
#distance
optimal=0
for i in range(len(route)-1):
    city_i=route[i]
    city_j=route[i+1]
    optimal=optimal+c[city_i][city_j]

In [19]:
print(f'The route to follow is:{route}' f'with a distance of {optimal} km')

The route to follow is:[0, 1, 2, 3, 0]with a distance of 118.6237 km


In [20]:
item_number=np.arange(len(route))
weight=list.copy(route)
value=[]
for i in range(len(weight)):
    value.append(1)
threshold=1000000000
print('The list is as follows:')
print('Item No.   Weight    Value')
for i in range(len(item_number)):
    print('{0}          {1}         {2}\n'.format(item_number[i], weight[i], value[i]))

The list is as follows:
Item No.   Weight    Value
0          0         1

1          1         1

2          2         1

3          3         1

4          0         1



In [21]:
solutions_per_pop = 100
pop_size = (solutions_per_pop, item_number.shape[0])
print('Population size = {}'.format(pop_size))
initial_population = np.random.randint(2, size = pop_size)
initial_population = initial_population.astype(int)
num_generations = 50
print('Initial population: \n{}'.format(initial_population))

Population size = (100, 5)
Initial population: 
[[1 0 1 0 1]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [1 1 0 0 1]
 [0 0 0 0 0]
 [1 0 1 1 1]
 [0 0 0 1 1]
 [0 1 0 0 1]
 [1 0 0 1 1]
 [0 0 1 0 0]
 [0 1 0 1 0]
 [0 1 0 1 1]
 [1 1 0 0 1]
 [0 0 1 1 0]
 [0 1 1 1 0]
 [0 1 1 0 0]
 [0 1 1 1 0]
 [0 1 0 0 1]
 [0 0 1 0 0]
 [0 1 0 0 1]
 [1 1 0 1 0]
 [0 0 1 0 1]
 [1 0 1 1 0]
 [0 0 0 0 0]
 [0 1 0 0 1]
 [0 1 0 0 0]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 0 0 1]
 [1 1 1 0 0]
 [1 0 1 1 0]
 [0 1 0 0 1]
 [0 0 1 0 0]
 [1 1 0 0 1]
 [0 0 0 1 0]
 [0 1 0 1 1]
 [0 1 1 0 1]
 [0 1 0 1 0]
 [1 1 0 0 0]
 [0 0 0 1 1]
 [0 1 0 0 0]
 [0 1 0 0 1]
 [1 1 0 0 0]
 [0 0 1 1 1]
 [1 1 1 0 1]
 [0 1 0 1 0]
 [1 1 0 1 1]
 [0 1 0 0 0]
 [1 1 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 1 1]
 [1 0 1 1 1]
 [0 1 1 1 1]
 [1 1 1 0 0]
 [1 0 1 0 0]
 [1 0 1 0 1]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 1 1 0 0]
 [0 1 0 1 1]
 [1 1 0 1 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 1 1]
 [0 0 0 0 0]
 [1 0 0 1 0]
 [1 0 1 1 1]
 [0 0 1 1 0]
 [0 1 1 1 1]
 [0

In [22]:
def cal_fitness(weight, value, population, threshold):
    fitness = np.empty(population.shape[0])
    for i in range(population.shape[0]):
        S1 = np.sum(population[i] * value)
        S2 = np.sum(population[i] * weight)
        if S2 <= threshold:
            fitness[i] = S1
        else :
            fitness[i] = 0 
    return fitness.astype(int)   

In [23]:
def selection(fitness, num_parents, population):
    fitness = list(fitness)
    parents = np.empty((num_parents, population.shape[1]))
    for i in range(num_parents):
        max_fitness_idx = np.where(fitness == np.max(fitness))
        parents[i,:] = population[max_fitness_idx[0][0], :]
        fitness[max_fitness_idx[0][0]] = -999999
    return parents

In [24]:
def crossover(parents, num_offsprings):
    offsprings = np.empty((num_offsprings, parents.shape[1]))
    crossover_point = int(parents.shape[1]/2)
    crossover_rate = 0.8
    i=0
    while (parents.shape[0] < num_offsprings):
        parent1_index = i%parents.shape[0]
        parent2_index = (i+1)%parents.shape[0]
        x = rndm.random()
        if x > crossover_rate:
            continue
        parent1_index = i%parents.shape[0]
        parent2_index = (i+1)%parents.shape[0]
        offsprings[i,0:crossover_point] = parents[parent1_index,0:crossover_point]
        offsprings[i,crossover_point:] = parents[parent2_index,crossover_point:]
        i=+1
    return offsprings    

In [25]:
def mutation(offsprings):
    mutants = np.empty((offsprings.shape))
    mutation_rate = 0.6
    for i in range(mutants.shape[0]):
        random_value = rd.random()
        mutants[i,:] = offsprings[i,:]
        if random_value > mutation_rate:
            continue
        int_random_value = randint(0,offsprings.shape[1]-1)    
        if mutants[i,int_random_value] == 0 :
            mutants[i,int_random_value] = 1
        else :
            mutants[i,int_random_value] = 0
    return mutants   

In [26]:
def optimize(weight, value, population, pop_size, num_generations, threshold):
    parameters, fitness_history = [], []
    num_parents = int(pop_size[0]/2)
    num_offsprings = pop_size[0] - num_parents 
    for i in range(num_generations):
        fitness = cal_fitness(weight, value, population, threshold)
        fitness_history.append(fitness)
        parents = selection(fitness, num_parents, population)
        offsprings = crossover(parents, num_offsprings)
        mutants = mutation(offsprings)
        population[0:parents.shape[0], :] = parents
        population[parents.shape[0]:, :] = mutants
        
    print('Last generation: \n{}\n'.format(population)) 
    fitness_last_gen = cal_fitness(weight, value, population, threshold)      
    print('Fitness of the last generation: \n{}\n'.format(fitness_last_gen))
    max_fitness = np.where(fitness_last_gen == np.max(fitness_last_gen))
    parameters.append(population[max_fitness[0][0],:])
    return parameters, fitness_history

In [27]:
parameters, fitness_history = optimize(weight, value, initial_population, pop_size, num_generations, threshold)
print('The optimized parameters for the given inputs are: \n{}'.format(parameters))
selected_items = item_number * parameters
print('\nRoute that will minimize distance:')
for i in range(selected_items.shape[1]):
  if selected_items[0][i] != 0:
     print('{}\n'.format(selected_items[0][i]))

Last generation: 
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 0 1 1]
 [1 1 1 0 1]
 [1 1 0 1 1]
 [1 0 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 0]
 [1 1 1 1 0]
 [1 1 1 1 1]
 [1 1 1 1 0]
 [1 1 1 0 1]
 [1 1 1 1 0]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 1 1 1 1]
 [1 1 0 1 1]
 [1 1 0 1 1]
 [1 1 1 1 1]
 [1 1 1 1 0]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 0 1]
 [0 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 0]
 [1 1 1